var nameList = {
    Time: "Time is precious. Use it wisely!",
    Past: "Don't dwell on the past, embrace the future!",
    Future: "Your future is what you make of it!",
    Dev: "Keep coding and creating amazing things!",
    Fly: "Soar high and achieve your dreams!",
    Flying: "Flying through challenges is what you do best!",
    Soar: "Soaring to new heights is in your nature!",
    Soaring: "Keep soaring, and never look back!",
    Power: "You have the power to change the world!",
    Falling: "Falling isn't failing. It's part of growing!",
    Fall: "Rise every time you fall!",
    Jump: "Leap into opportunities with confidence!",
    Cliff: "Stand tall, even at the edge of challenges.",
    Mountain: "Every mountain is conquerable!",
    Rend: "Tear through the obstacles in your way!",
    Red: "Bold, strong, and unstoppable!",
    Blue: "Calm, cool, and collected like the ocean.",
    Green: "Fresh, vibrant, and full of life!",
    Yellow: "Shine bright like the sun!",
    Gold: "Your potential is worth its weight in gold!",
    Demon: "Unleash your inner fire to achieve greatness!",
    Demonic: "Channel your energy to overcome all odds!",
    Panda: "Stay cool and cuddly, but fierce when needed!",
    Cat: "Graceful, agile, and independent!",
    Kitty: "Small yet mighty, just like you!",
    Kitten: "Adorable but ready to pounce on goals!",
    Zero: "Start at zero, aim for infinity!",
    Memory: "Create memories that last forever!",
    Trooper: "Keep marching forward, no matter what!",
    XX: "Double the power, double the fun!",
    Bandit: "Stealing the show wherever you go!",
    Fear: "Face your fears and conquer them!",
    Light: "Be the light in someone's darkness.",
    Glow: "Let your glow inspire others!",
    Tread: "Walk boldly, leaving a trail behind.",
    Deep: "Dive deep into your passions!",
    Deeper: "Go deeper into the unexplored.",
    Deepest: "Discover the deepest parts of yourself!",
    Mine: "Claim what's yours with determination!",
    Your: "Your story is waiting to be written.",
    Worst: "Turn your worst moments into strength!",
    Enemy: "Your only enemy is your doubt.",
    Hostile: "Overcome hostility with perseverance!",
    Force: "Use your inner force to create change!",
    Video: "Create a video-worthy story of your life!",
    Game: "Life is a game—play it well!",
    Donkey: "Stay humble but persistent like a donkey!",
    Mule: "Stubbornness can sometimes be a strength!",
    Colt: "Young and full of potential!",
    Cult: "Start a movement that inspires!",
    Cultist: "Dedication leads to mastery!",
    Magnum: "Think big, act bigger!",
    Gun: "Stay sharp and hit your targets!",
    Assault: "Approach challenges head-on!",
    Recon: "Strategize before you leap!",
    Trap: "Don't fall into traps; set your own!",
    Trapper: "Be ready to catch opportunities!",
    Redeem: "Every day is a chance to redeem yourself!",
    Code: "Keep coding and change the world!",
    Script: "Your life script is in your hands!",
    Writer: "Write your story, your way!",
    Near: "Great things are nearer than you think!",
    Close: "You're closer to success than you realize!",
    Open: "Keep an open mind for endless possibilities!",
    Cube: "Think outside the box!",
    Circle: "Stay connected with those around you!",
    Geo: "Explore the world and its wonders!",
    Genome: "Your uniqueness is your strength!",
    Germ: "Small ideas can lead to big changes!",
    Spaz: "Let your energy fuel your creativity!",
    Shot: "Take your best shot at life!",
    Echo: "Let your voice echo in the world!",
    Beta: "Be a work in progress—always improving!",
    Alpha: "Lead the pack with confidence!",
    Gamma: "Energize your goals with gamma-like focus!",
    Omega: "The end is just the beginning!",
    Seal: "Seal your success with determination!",
    Squid: "Adapt to every challenge, like a squid!",
    Money: "Value your worth beyond money!",
    Cash: "Earn respect, not just cash!",
    Lord: "Rule your world with humility!",
    King: "Be the king of your destiny!",
    Duke: "Carry yourself with noble grace!",
    Rest: "Rest is just as important as work!",
    Fire: "Let your passion burn bright!",
    Flame: "Fuel your flame with positivity!",
    Morrow: "A new morrow brings new opportunities!",
    Break: "Take breaks, not breakdowns!",
    Breaker: "Break through the barriers ahead!",
    Numb: "Feel everything, even in numbness!",
    Ice: "Stay cool, even under pressure!",
    Cold: "Face the cold truth with courage!",
    Rotten: "Turn rotten situations into growth!",
    Sick: "Heal your doubts and rise strong!",
    Sickly: "Don't let sickly days hold you back!",
    Janitor: "Keep your life clean and organized!",
    Camel: "Endure life's deserts with patience!",
    Rooster: "Rise early and chase your dreams!",
    Sand: "Build castles from the sands of time!",
    Desert: "Navigate life's deserts with wisdom!",
    Dessert: "Sweeten your life with small joys!",
    Extreme: "Take life to the extreme and thrive!",
    Big: "Dream big, act bigger!",
    Small: "Small steps lead to big achievements!",
};
export function generateRandomName() {
    const keys = Object.keys(nameList); // Get all keys from the object
    const randomKey = keys[Math.floor(Math.random() * keys.length)]; // Select a random key
    return { name: randomKey, message: nameList[randomKey] }; // Return both key and value as an object
  }
  